export const TYPES = {
	SET_PARTIAL_MOVIES: 'SET_PARTIAL_MOVIES',
	MOVIES_LOADING_STARTED: 'MOVIES_LOADING_STARTED',
	SET_ALL_MOVIES: 'SET_ALL_MOVIES',
	FILTER_MOVIES: 'FILTER_MOVIES',
	REMOVE_MOVIE: 'REMOVE_MOVIE',
	SORT_MOVIES: 'SORT_MOVIES',
	SEARCH_MOVIES: 'SEARCH_MOVIES',
	SET_MOVIE_DETAILS: 'SET_MOVIE_DETAILS',
	CLEAR_MOVIE_DETAILS: 'CLEAR_MOVIE_DETAILS',
	CREATE_ERROR: 'CREATE_ERROR',
	CLEAR_ERROR: 'CLEAR_ERROR'
};
